# Generated by Django 5.0.3 on 2024-04-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='houses/%Y/%m/%d/')),
                ('slider_image_1', models.ImageField(upload_to='houses/%Y/%m/%d/')),
                ('slider_image_2', models.ImageField(upload_to='houses/%Y/%m/%d/')),
                ('slider_image_3', models.ImageField(upload_to='houses/%Y/%m/%d/')),
                ('slider_image_4', models.ImageField(upload_to='houses/%Y/%m/%d/')),
                ('slider_image_5', models.ImageField(upload_to='houses/%Y/%m/%d/')),
                ('slider_image_6', models.ImageField(upload_to='houses/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('garages', models.CharField(max_length=50)),
                ('area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=8)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
