# Generated by Django 5.0.3 on 2024-04-02 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_realtor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Realtor',
        ),
    ]
