# Generated by Django 5.0.3 on 2024-04-02 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_realtorprofile_datetimefield_and_more'),
        ('listings', '0004_listing_customer_listing_realtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customerprofile'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.realtorprofile'),
        ),
    ]
