# Generated by Django 5.0.3 on 2024-04-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_annonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
