# Generated by Django 5.0.4 on 2024-04-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='transaction_type',
            field=models.CharField(choices=[('allouer', 'Allouer'), ('vendre', 'Vendre')], default='vendre', max_length=50),
        ),
    ]
