# Generated by Django 5.0.3 on 2024-04-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='realstor',
            new_name='listings',
        ),
        migrations.AddField(
            model_name='order',
            name='has_arrived',
            field=models.BooleanField(default=False),
        ),
    ]
