# Generated by Django 5.0.4 on 2024-04-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_payment_status_order_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_type',
            field=models.CharField(choices=[('allouer', 'allouer'), ('vendre', 'vendre')], default='vendre', max_length=50),
            preserve_default=False,
        ),
    ]
