# Generated by Django 5.0.4 on 2024-04-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contact_last_answer_contact_response_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('par versement', 'In Installements'), ('par contrat de location', 'Contract'), ('payee', 'Cash')], default='payee', max_length=23),
        ),
    ]
