# Generated by Django 5.0.4 on 2024-04-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='arrival_date',
        ),
        migrations.AddField(
            model_name='order',
            name='rent_or_installement_payement_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
