# Generated by Django 5.0.3 on 2024-04-02 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(upload_to='profiles/%y/%m/%d/')),
                ('status', models.CharField(choices=[('GUEST', 'Guest'), ('PREMIUM', 'PREMIUM'), ('NORMAL', 'NORMAL')], max_length=10)),
                ('perferances', models.TextField()),
                ('search_history', models.TextField()),
                ('background', models.TextField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RealtorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(upload_to='realtors/%Y/%m/%d/')),
                ('biographie', models.TextField()),
                ('is_seller_of_month', models.BooleanField()),
                ('affiliation_date', models.DateField()),
                ('datetimefield', models.DateTimeField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
