# Generated by Django 5.0.3 on 2024-04-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_realtorprofile_datetimefield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='is_month_seler',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
