# Generated by Django 5.0.3 on 2024-04-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_is_month_seler_customerprofile_is_month_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='status',
            field=models.CharField(choices=[('Guest', 'Guest'), ('PREMIUM', 'Premium'), ('Normal', 'Normal')], max_length=10),
        ),
    ]
