# Generated by Django 5.0.4 on 2024-04-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customerprofile_is_month_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='profile_image',
            field=models.ImageField(default='customer-default.png', upload_to='profiles/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='designerprofile',
            name='profile_image',
            field=models.ImageField(default='designer-default.png', upload_to='designers/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='realtorprofile',
            name='profile_image',
            field=models.ImageField(default='realtor-default.png', upload_to='realtors/%Y/%m/%d/'),
        ),
    ]
