# Generated by Django 5.0.4 on 2024-04-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_realtorprofile_is_seller_of_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtorprofile',
            name='affiliation_date',
            field=models.DateField(auto_now=True),
        ),
    ]
